#!/usr/bin/env python3
"""
Enrich a marker-produced Markdown file by converting every referenced figure
into an agent-parseable text block (SysML v2, PlantUML, data table, or dense
prose) placed directly beneath the figure reference.

Usage:
    enrich-figures.py <markdown_file> [--ollama-url URL] [--model NAME]
                                      [--prompts-dir DIR]
"""
from __future__ import annotations

import argparse
import base64
import json
import pathlib
import re
import sys
import urllib.request
import urllib.error


IMAGE_RE = re.compile(r'^!\[(?P<alt>[^\]]*)\]\((?P<path>[^)]+)\)\s*$', re.MULTILINE)
ENRICHED_MARKER = "<!-- enriched:figure -->"

VALID_MODALITIES = {
    "technical_drawing",
    "schematic",
    "chart",
    "table_as_image",
    "photo",
    "equation_as_image",
    "other",
}


def ollama_vision(url: str, model: str, prompt: str, image_b64: str,
                  timeout: int = 300) -> str:
    """Call ollama /api/generate with a vision model. Returns response text."""
    payload = {
        "model": model,
        "prompt": prompt,
        "images": [image_b64],
        "stream": False,
        "options": {"temperature": 0.1},
    }
    req = urllib.request.Request(
        f"{url}/api/generate",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8")).get("response", "").strip()
    except urllib.error.URLError as exc:
        print(f"   ! ollama error: {exc}", file=sys.stderr)
        return ""


def classify(image_b64: str, url: str, model: str, prompt_tmpl: str) -> str:
    raw = ollama_vision(url, model, prompt_tmpl, image_b64).lower()
    for modality in VALID_MODALITIES:
        if modality in raw:
            return modality
    return "other"


def enrich(image_b64: str, modality: str, url: str, model: str,
           prompts: dict[str, str]) -> str:
    prompt = prompts.get(modality, prompts["other"])
    body = ollama_vision(url, model, prompt, image_b64)
    if not body:
        body = ("**[ENRICHMENT FAILED]** — vision model returned empty response. "
                "Review figure manually.")

    fenced_modalities = {
        "technical_drawing": "sysml",
        "schematic": "plantuml",
        "chart": "",  # chart returns Markdown table natively
        "equation_as_image": "latex",
    }
    fence_lang = fenced_modalities.get(modality)

    header = (
        f"{ENRICHED_MARKER}\n\n"
        f"**Figure modality:** `{modality}`  \n"
        f"**Agent-parseable representation** "
        f"(auto-generated by qwen2.5vl — verify before relying on it):\n"
    )

    if fence_lang is not None and fence_lang != "":
        # Strip any fenced blocks the model may have already added, then re-fence cleanly.
        stripped = re.sub(r"^```[a-zA-Z]*\n|```$", "", body.strip(),
                          flags=re.MULTILINE).strip()
        return f"\n{header}\n```{fence_lang}\n{stripped}\n```\n"
    return f"\n{header}\n{body}\n"


def load_prompts(prompts_dir: pathlib.Path) -> dict[str, str]:
    mapping = {
        "classify":           "classify-figure.txt",
        "technical_drawing":  "technical-drawing-to-sysmlv2.txt",
        "schematic":          "schematic-to-plantuml.txt",
        "chart":              "chart-to-table.txt",
        "table_as_image":     "verify-table.txt",
        "photo":              "photo-to-prose.txt",
        "equation_as_image":  "equation-to-latex.txt",
        "other":              "photo-to-prose.txt",
    }
    out = {}
    for key, fname in mapping.items():
        path = prompts_dir / fname
        if not path.is_file():
            print(f"WARNING: missing prompt file {path}", file=sys.stderr)
            out[key] = "Describe this image in rigorous, factual detail."
            continue
        out[key] = path.read_text(encoding="utf-8")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("markdown_file", type=pathlib.Path)
    ap.add_argument("--ollama-url", default="http://localhost:11434")
    ap.add_argument("--model", default="qwen2.5vl:7b")
    ap.add_argument("--prompts-dir", type=pathlib.Path, required=True)
    args = ap.parse_args()

    md_path: pathlib.Path = args.markdown_file.resolve()
    if not md_path.is_file():
        print(f"ERROR: {md_path} not found", file=sys.stderr)
        return 1

    prompts = load_prompts(args.prompts_dir)
    text = md_path.read_text(encoding="utf-8")
    assets_root = md_path.parent

    # Find all image refs not already enriched.
    matches = list(IMAGE_RE.finditer(text))
    if not matches:
        print("   (no figures found)")
        return 0

    # Process from bottom to top to keep offsets valid.
    replacements: list[tuple[int, int, str]] = []
    for idx, m in enumerate(matches, start=1):
        img_rel = m.group("path").strip()
        alt = m.group("alt")

        # Skip if already enriched (next non-blank line contains marker)
        tail = text[m.end():m.end() + 400]
        if ENRICHED_MARKER in tail.split("\n\n", 1)[0] + tail:
            continue

        img_path = (assets_root / img_rel).resolve()
        if not img_path.is_file():
            print(f"   [{idx}/{len(matches)}] missing asset: {img_rel} — skipped")
            continue

        try:
            image_b64 = base64.b64encode(img_path.read_bytes()).decode("ascii")
        except OSError as exc:
            print(f"   [{idx}/{len(matches)}] read error {img_rel}: {exc}")
            continue

        print(f"   [{idx}/{len(matches)}] {img_rel} — classifying...", flush=True)
        modality = classify(image_b64, args.ollama_url, args.model,
                            prompts["classify"])
        print(f"        → {modality}; enriching...", flush=True)
        enrichment = enrich(image_b64, modality, args.ollama_url, args.model, prompts)

        block = m.group(0)
        if alt:
            caption = f"\n*Original caption:* {alt}\n"
        else:
            caption = ""
        replacement = f"{block}{caption}{enrichment}"
        replacements.append((m.start(), m.end(), replacement))

    # Apply replacements bottom-up.
    for start, end, new in reversed(replacements):
        text = text[:start] + new + text[end:]

    md_path.write_text(text, encoding="utf-8")
    print(f"   enriched {len(replacements)} figure(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
